"""
Data Preparation Module
=======================
Loads raw CSVs, cleans, validates, merges, creates the churn label,
and produces a single analysis-ready dataset with train/test splits.

TEMPORAL DESIGN:
- Features are computed from data BEFORE the prediction date (June 1)
- Churn label is determined from data AFTER the prediction date (June 1-30)
- This prevents data leakage and simulates a real production scenario

Assumptions:
- Raw data lives in data/raw/ (generated by generate_synthetic_data.py)
- Prediction date: 2025-06-01
- Churn window: June 1-30 (user churned if they effectively stop using the platform)
- Stratified 80/20 train/test split
"""

import os
import pandas as pd
from sklearn.model_selection import train_test_split

# Paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW_DIR = os.path.join(BASE_DIR, "data", "raw")
PROCESSED_DIR = os.path.join(BASE_DIR, "data", "processed")

PREDICTION_DATE = pd.Timestamp("2025-06-01")
OBSERVATION_END = pd.Timestamp("2025-06-30")


def load_raw_data() -> dict:
    """Load all raw CSV files into DataFrames."""
    print("Loading raw data...")
    data = {
        "users": pd.read_csv(
            os.path.join(RAW_DIR, "users.csv"), parse_dates=["signup_date"]
        ),
        "orders": pd.read_csv(
            os.path.join(RAW_DIR, "orders.csv"), parse_dates=["order_date"]
        ),
        "subscriptions": pd.read_csv(
            os.path.join(RAW_DIR, "subscriptions.csv"),
            parse_dates=["plan_start", "plan_end"],
        ),
        "engagement": pd.read_csv(
            os.path.join(RAW_DIR, "engagement.csv"), parse_dates=["date"]
        ),
    }

    for name, df in data.items():
        print(f"  {name}: {df.shape[0]:,} rows, {df.shape[1]} columns")

    return data


def clean_data(data: dict) -> dict:
    """Clean and validate each DataFrame."""
    print("Cleaning data...")

    # Users: drop duplicates, validate types
    users = data["users"].drop_duplicates(subset=["user_id"])
    users["age"] = users["age"].clip(18, 80)

    # Orders: remove invalid values, drop duplicates
    orders = data["orders"].drop_duplicates(subset=["order_id"])
    orders = orders[orders["order_value"] > 0]
    orders["rating"] = orders["rating"].clip(1.0, 5.0)

    # Subscriptions: ensure valid date ranges
    subs = data["subscriptions"].drop_duplicates(subset=["user_id"])
    subs = subs[subs["plan_end"] >= subs["plan_start"]]

    # Engagement: drop duplicates, fill NaNs with 0
    engagement = data["engagement"].drop_duplicates(subset=["user_id", "date"])
    engagement = engagement.fillna(0)

    print("  Duplicates removed, invalid values cleaned")
    return {
        "users": users,
        "orders": orders,
        "subscriptions": subs,
        "engagement": engagement,
    }


def create_churn_label(
    users: pd.DataFrame, orders: pd.DataFrame, subs: pd.DataFrame
) -> pd.DataFrame:
    """Create the binary churn label based on behavior in the churn window (June).

    A user is considered churned if:
    1. They placed 0 or very few orders in June (churn window), AND
    2. They did not renew their subscription

    NOTE: The churn label comes from the `is_churned` column in users.csv,
    which was set during data generation based on the user's simulated behavior.
    We validate it here against the actual June order/subscription data.
    """
    print("Creating churn labels...")

    # Count orders in the churn window (June)
    june_orders = (
        orders[
            (orders["order_date"] >= PREDICTION_DATE)
            & (orders["order_date"] <= OBSERVATION_END)
        ]
        .groupby("user_id")
        .size()
        .reset_index(name="june_orders")
    )

    # Build labeled dataset
    labeled = users[
        [
            "user_id",
            "signup_date",
            "subscription_plan",
            "dietary_preference",
            "fitness_goal",
            "age",
            "city",
            "is_churned",
        ]
    ].copy()
    labeled = labeled.merge(june_orders, on="user_id", how="left")
    labeled["june_orders"] = labeled["june_orders"].fillna(0).astype(int)

    # Subscription renewal status
    labeled = labeled.merge(subs[["user_id", "is_renewed"]], on="user_id", how="left")
    labeled["is_renewed"] = labeled["is_renewed"].fillna(0).astype(int)

    # Use the pre-assigned churn label (from data generation)
    labeled["churned"] = labeled["is_churned"]

    churn_rate = labeled["churned"].mean()
    print(
        f"  Churn rate: {churn_rate:.1%} ({labeled['churned'].sum():,} / {len(labeled):,})"
    )
    print(
        f"  Churned users with June orders: {labeled[(labeled['churned'] == 1) & (labeled['june_orders'] > 0)].shape[0]}"
    )
    print(f"  Loyal users: {labeled[labeled['churned'] == 0].shape[0]:,}")

    return labeled


def prepare_dataset() -> tuple:
    """Full data preparation pipeline.

    Returns:
        Tuple of (train_df, test_df, merged_data_dict)
    """
    # Load
    data = load_raw_data()

    # Clean
    data = clean_data(data)

    # Create labels
    labeled_users = create_churn_label(
        data["users"], data["orders"], data["subscriptions"]
    )

    # Save intermediate
    os.makedirs(PROCESSED_DIR, exist_ok=True)

    # Separate feature-period data (before prediction date) for feature engineering
    feature_orders = data["orders"][
        data["orders"]["order_date"] < PREDICTION_DATE
    ].copy()
    feature_engagement = data["engagement"][
        data["engagement"]["date"] < PREDICTION_DATE
    ].copy()

    print(f"\n  Feature-period orders: {len(feature_orders):,}")
    print(f"  Feature-period engagement: {len(feature_engagement):,}")

    merged = {
        "users": labeled_users,
        "orders": feature_orders,  # ONLY pre-prediction orders for features
        "subscriptions": data["subscriptions"],
        "engagement": feature_engagement,  # ONLY pre-prediction engagement for features
    }

    # Save labeled users
    labeled_users.to_csv(os.path.join(PROCESSED_DIR, "labeled_users.csv"), index=False)
    print(f"\n  Labeled users saved to {PROCESSED_DIR}/labeled_users.csv")

    # Stratified train/test split
    train_users, test_users = train_test_split(
        labeled_users, test_size=0.2, random_state=42, stratify=labeled_users["churned"]
    )
    print(f"  Train: {len(train_users):,} users | Test: {len(test_users):,} users")

    return train_users, test_users, merged


if __name__ == "__main__":
    print("=" * 60)
    print("Haett Data Preparation Pipeline")
    print("=" * 60)
    train, test, merged = prepare_dataset()
    print("\n✅ Data preparation complete")
